________________________________________________________________________________________________________________________


* Yuvraj Sutar 
* yuvrajsutar009@gmail.com
_ _________________________________________________________________________________________________________________________
_  _________________________________________________________________________________________________________________________

# NumPy 


NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [ ]:
pip install numpy

## Using NumPy


Using NumPy, a developer can perform the following operations −

* Mathematical and logical operations on arrays.



* Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation

**Once you've installed NumPy you can import it as a library:**


In [4]:
import numpy as np


In [5]:

np.array([1,2,3])


array([1, 2, 3])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.



# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).



The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. 

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays



In [6]:
# one dimension 

my_array = np.array([1,2,3,4,5]) 
my_array.shape

(5,)

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)


array([1, 2, 3])

In [9]:
# more than one dimensions 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mat=np.array(my_matrix)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Shape

In [11]:
mat.shape

(3, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.



### Some Exapmles



In [12]:
np.arange(2,10,3)

array([2, 5, 8])

In [13]:
np.arange(0,11,4)

array([0, 4, 8])

### zeros and ones

Generate arrays of zeros or ones



In [14]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In this function, instead of step size, the number of evenly spaced values between the interval is specified.



In [18]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye or identity


Creates an identity matrix


In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:



### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(1,100,10)

array([[[8.18434935e-01, 7.86552167e-01, 3.47101010e-01, 2.49856120e-01,
         2.56444056e-01, 7.86749934e-01, 2.05029048e-01, 4.65590648e-01,
         1.77087325e-01, 6.05383380e-01],
        [2.22310977e-01, 2.02456853e-01, 4.36074160e-01, 7.88298810e-01,
         9.50929570e-01, 7.47397944e-01, 3.79733941e-01, 4.98336376e-01,
         4.02835608e-01, 9.82172509e-01],
        [2.60750221e-01, 8.41390909e-01, 8.33865255e-01, 4.11693873e-01,
         5.71179164e-02, 7.97775923e-01, 8.28442374e-01, 2.09795184e-01,
         5.26438006e-01, 8.63470037e-01],
        [6.96422660e-01, 2.08920340e-01, 7.31928583e-01, 3.28197276e-01,
         3.03106451e-01, 2.01860956e-01, 7.32780819e-01, 4.88632784e-01,
         4.30230748e-01, 9.24934498e-01],
        [1.94770959e-01, 8.69735498e-01, 8.30280235e-01, 7.02411261e-01,
         6.02870918e-01, 8.40485439e-01, 3.20420589e-01, 9.78029749e-01,
         8.64379520e-01, 8.36008474e-01],
        [3.85910035e-01, 1.15928889e-02, 1.07440296e-01, 8.4

In [23]:
np.random.rand(5,5)

array([[0.16937862, 0.85446404, 0.20135778, 0.21207375, 0.16277028],
       [0.52073847, 0.74221436, 0.83808185, 0.09136486, 0.33228444],
       [0.6246569 , 0.05170389, 0.61730444, 0.42707919, 0.67300372],
       [0.30461452, 0.61713073, 0.86011335, 0.40728099, 0.31719222],
       [0.33520761, 0.33958854, 0.10827116, 0.41661841, 0.75169315]])

In [24]:
np.random.randn(50)

array([ 1.12745566, -0.53447017, -0.52676071, -0.63066668,  0.06394914,
        0.15587379, -1.08106035, -0.71053913, -1.75579292,  0.69397763,
       -0.24397153, -0.419776  ,  1.09222008,  1.67503483,  0.89883655,
       -0.55427311,  0.7151794 , -1.21461311,  0.10929255, -2.66685733,
       -0.96348588, -0.78445574,  0.55190084,  0.4457643 ,  0.31073669,
        0.32583991,  1.15295385, -1.12108541,  0.78463827, -0.15989334,
       -0.58045145,  2.04436121,  1.3640149 , -0.29488182, -0.49652568,
       -0.49620885, -1.41488687,  0.70767813,  1.17597962, -1.095491  ,
       -1.0806195 , -0.70708186,  2.56303451,  0.46919909,  0.61490742,
       -0.50083921, -0.01550287, -1.47948531,  0.14903146, -0.82748762])

### randn



Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-1.6499455 ,  0.17995426])

In [26]:
np.random.randn(5,5).shape

(5, 5)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,20)

6

In [28]:
np.random.randint(1,101,20)

array([  3,  62,  83,   8,  91,  45,  47,  12,  10,  83, 100,  60,  76,
        98,  99,   3,  83,  42,  16,  45])

## Array Attributes 

Let's discuss some useful attributes and methods or an array:

In [29]:
import numpy as np
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
len(arr)

25

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.



In [32]:
arr.reshape(5,5,)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Matrix Aggregation

### max,min,argmax,argmin,Sum

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax


In [56]:
arr = np.random.randint(0,50,25)
arr

array([46, 38, 20, 29, 12,  9, 17, 16, 37, 38, 49, 31, 41, 34, 27, 43, 29,
       35, 22,  3, 40,  7,  8, 20,  9])

In [57]:
arr.max()

49

In [58]:
arr.argmax()

10

In [59]:
arr.min()

3

In [60]:
arr.argmin()

19

In [61]:
arr.sum()

660

..............................................................................................................................................................................................................................................................

## Shape

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array. :

In [62]:
# Vector
arr.shape

(25,)

In [64]:
# Notice the two sets of brackets
arr.reshape(5,5)

array([[46, 38, 20, 29, 12],
       [ 9, 17, 16, 37, 38],
       [49, 31, 41, 34, 27],
       [43, 29, 35, 22,  3],
       [40,  7,  8, 20,  9]])

In [65]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [66]:
arr.reshape(25,1).shape

(25, 1)

* Yuvraj Sutar 
* yuvrajsutar009@gmail.com

# Great Job!