________________________________________________________________________________________________________________________


* Yuvraj Sutar 
* yuvrajsutar009@gmail.com
_ _________________________________________________________________________________________________________________________
_  _________________________________________________________________________________________________________________________

## NumPy Indexing and Selection

#### In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(11,22)

In [3]:
#Show
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

## Bracket Indexing and Selection

## 1D Array

The simplest way to pick one or some elements of an array looks very similar to python lists:



In [4]:
#Get a value at an index
arr[-1]


21

In [5]:
#Get values in a range
arr[0:6:2]   #[start : Stop: Step]


array([11, 13, 15])

In [6]:
#Get values in a range
arr[0:5]

array([11, 12, 13, 14, 15])

In [7]:
mat=np.array([[4,5,6],[1,2,3]])
mat

array([[4, 5, 6],
       [1, 2, 3]])

In [8]:
mat[1]

array([1, 2, 3])

In [9]:
arr = np.arange(11,22)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

## slicing


Slicing is basically extracting particular set of elements from an array.


In [11]:
import numpy as np
arr = np.arange(11,4)
arr


array([], dtype=int32)

In [12]:
arr[:]

array([], dtype=int32)

In [13]:
#Important notes on Slices
slice_of_arr = arr[:]

#Show slice
slice_of_arr

array([], dtype=int32)

In [14]:
s = arr[0:6]
print (s)

[]


In [15]:
#Change Slice
slice_of_arr[2:]


array([], dtype=int32)

In [16]:

#Show Slice again
slice_of_arr[5:]

array([], dtype=int32)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.


In [17]:
import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
# 2D array slicing

#Shape (2,2) 
arr_2d[1:,0:2]   #[row,col]

array([[20, 25],
       [35, 40]])

In [37]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [28]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[2,2]

45

In [27]:
# Getting individual element value
arr_2d[1,1]

25

In [19]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[arr < 4]

array([1, 2, 3])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

* Yuvraj Sutar 
* yuvrajsutar009@gmail.com

# Great Job!
