________________________________________________________________________________________________________________________


* Yuvraj Sutar 
* yuvrajsutar009@gmail.com
_ _________________________________________________________________________________________________________________________
_  _________________________________________________________________________________________________________________________


# NumPy Operations


## Arithmetic



Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules.

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:



In [1]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
arr*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [3]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [4]:
arr / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [5]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_16180/2878212635.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_16180/1360216608.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

## power



In [8]:
arr**3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

## dot product

A key distinction to make with arithmetic is the case of matrix multiplication using the dot product. NumPy gives every matrix a dot() method we can use to carry-out dot product operations with other matrices:



In [9]:
a = np.array([[1,2],[3,4]]).shape
a


(2, 2)

In [10]:
b = np.array([[11,12],[13,14]]).shape
b

(2, 2)

In [11]:
#11*1 + 2*13 = 37           1*12 + 2 *14 =40
#3*11 + 4*13 = 33+52=85      3*12 +4*14= 92
np.dot(a,b)


8

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

## square root


In [14]:
#Taking Square Roots
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

## exponential



In [15]:
#Calcualting exponential (e^)
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [16]:
np.max(arr) #same as arr.max()

8

## Trigonometric Functions
NumPy has standard trigonometric functions which return trigonometric ratios for a given angle in radians.



In [17]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

## log function



In [18]:
np.log(arr)

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_15056/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

## Function for Rounding



This is a function that returns the value rounded to the desired precision.



In [19]:
z = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:' )
print (z) 
print ('\n'  )

print ('After rounding:' )
print (np.around(z) )
print(np.around(z, decimals = 2) )



Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.     5.55 123.     0.57  25.53]


* Yuvraj Sutar 
* yuvrajsutar009@gmail.com

# Great Job!
